name: Test

on:
  push:
    branches:
      - "**"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - name: Run tests
        run: npm run test
